server:
  port: 8080
application:
  link:
    request: http://localhost:8081/smev/request/put/
    getAnswer: http://localhost:8081/smev/response/
    confirm: http://localhost:8081/smev/response/confirm/
